### PR TITLE
#38

### PR DESCRIPTION
**Pull request by nemaniarjun**
WIP
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by nemaniarjun** [comment]
@TimVanMourik give this a look when you can

**Comment by TimVanMourik** [comment]
Yes, perfect! Very nicely coded as well. The visuals of the progress bar will probably be updated in the not too distant future and with this back-end that's perfectly doable. With this, I just checked the box on issue #84 👍

**Comment by nemaniarjun** [comment]
@TimVanMourik Push the error logging commit and also a new commit to persist coala cache across runs. This will speed up consequent runs (as coala will only run on changed files)
Right now I have set the volume location to be `/tmp/cache`. Where do I place the same in Windows? Ideally somewhere that is cleared across restarts. Also where can we check the OS and use the corresponding volume location?

**Comment by TimVanMourik** [comment]
I will have a look at this later this week! But my first impression: Docker is a bit awkward as soon as you start using absolute file paths, so I'm not generally in favour of it. I would have to think about if instead a local logging directory is a smart move. I cannot think of another platform-independent solution to this.

**Comment by nemaniarjun** [comment]
I think you mean local caching directory here. 
Maybe we can keep it relative and add to the contributing guide that users can safely/should frequently delete those files?

**Comment by TimVanMourik** [comment]
So I was a bit cryptic because I was in a hurry when I looked at it last Sunday night. I was indeed referring to the specific question that you asked about the docker part.

And the main part of this PR looks great too! I already mentioned previously that the loading and the the progress bar are implemented well, and the error checking looks good too. I see that you pass on another context variable from the Django part of the app, and that's perfect. I think in a later iteration we'll put some effort in displaying the error message, but it's all good for now. 

So last box is checked. I'll tip you for this work with  0.1 ETH, as mentioned in the issue post #84, ok?

**Comment by nemaniarjun** [comment]
Sounds great! I will make a new issue and PR for the coala logging thing, and prep this for merging.

**Pull request merged**
