### PR TITLE
[React] Hover event on node, provide a tooltip

### PR DESCRIPTION
**Pull request by maryam21**
## Description

 
- Hovering on a node shows a tooltip with all parameters and their current values
- When a node has more than 10 parameters the tooltip only shows defined ones.

## Related Issue

Refers to #34 
## Motivation and Context

#34 
## How Has This Been Tested?

Locally.
## Screenshots (if appropriate):
porcupinescreen

when there are more than 10 parameters:

porcupine2 2

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by TimVanMourik** [comment]
Thanks for the WIP @maryam21! As #37 is finished now, I updated the brief and funded the issue.

**Comment by TimVanMourik** [comment]
Hi @maryam21, I’ve seen commits dripping in on this PR, but could you please let me know when it’s done or give me an update abuot the status and the plan?

**Comment by maryam21** [comment]
Hi @TimVanMourik , I am sorry I didn't give an update. I will be able to finish this in 2 days maximum.

**Comment by maryam21** [comment]
Hi @TimVanMourik , I finished working on this you can review it now. I wanted to submit work through gitcoin but couldn't find how to do it :-/.

**Comment by TimVanMourik** [comment]
Awesome @maryam21, thank you very much! By the looks of it it's a working solution! I'll review it tomorrow first thing in the morning. Just one question about the code that I'm spotting right now: you've implemented a 'hover' and a 'leave' event. I got the impression that hovering by definition captures entering and leaving, so could you briefly explain to me the purpose of the leave event? Thanks!

Please submit a claim to the bounty! You can do so by going to [this link](https://gitcoin.co/issue/TimVanMourik/GiraffeTools/34/465) and there should be a submit button. Provided that you're logged in with GitHub and Metamask is activated. There was some recent trouble with this on an other bounty, so let me know if this doesn't work. Then I'll inform the Gitcoin developers.

**Comment by maryam21** [comment]
Thanks @TimVanMourik . I added the leave event so that I could set 'hoveredNode' to null when the mouse leaves the node, because instead it will keep the ReactTooltip in the DOM since 'hoveredNode' is still set to the previous node. And in case of multiple nodes the ReactTooltip will only show for the first node.

**Pull request merged**
