### PR TITLE
fix to issue #54: Codecov doesn't work anymore since pytest update

### PR DESCRIPTION
**Pull request by aditya-jha**
Switching from `pytest` to `python manage.py test` was not generating the `.coverage` file
Updating the commands seems to have solved the issue.

## Description
Changed `python manage.py test` to `coverage run ./manage.py test --noinput --settings=app.settings.local`

## Related Issue
https://github.com/TimVanMourik/GiraffeTools/issues/54

## How Has This Been Tested?
I have checked that `.coverage` file is getting generated upon running the tests

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by TimVanMourik** [comment]
Ok, great! This produces a report and doesn't break Travis. But.. it looks like the report overwrites the pytest report. Or am I missing something?

**Comment by TimVanMourik** [comment]
It looks like a `coverage cobine [ ] ` might do the trick!

**Comment by aditya-jha** [comment]
I guess `coverage combine` is for python tests only.
According to this (https://docs.codecov.io/docs/merging-reports) , codecov will manage multiple reports if uploaded separately.

should I update
after_success:
  - bash <(curl -s https://codecov.io/bash) -cF python
  - bash <(curl -s https://codecov.io/bash) -cF javascript

**Comment by TimVanMourik** [comment]
Ah, sorry for the red herring, you're right! This seems much better indeed. It now seems to cover both tests, although I'm a bit confused by:

> | Flag | Coverage Δ | |
> |---|---|---|
> | #javascript | `70.16% <ø> (?)` | |
> | #python | `70.16% <ø> (?)` | |

I'd say the javascript coverage shuold be a lot lower, so I'm wondering if this is all correct now.

**Comment by aditya-jha** [comment]
According to this
=========================================
  Coverage          ?   70.16%           
=========================================
  Files             ?       23           
  Lines             ?      476           
  Branches          ?        0           
=========================================
  Hits              ?      334           
  Misses            ?      142           
  Partials          ?        0

I am guessing because of the merge, the coverage is overall test coverage and not independent. However, if this is true then python and js values shouldn't have been shown separate.

Also, if the results are incorrect, I guess it becomes a separate issue, isn't it?

I am not sure where to look for possible issues to verify the results. Guide me forward.

**Comment by TimVanMourik** [comment]
Would it make sense to still run pip install codecov && codecov and only then upload the reports with your newly added lines? Because before that, the `npm test` bit was still working and it was only missing out on the python files.

**Comment by aditya-jha** [comment]
something like this?
`after_success:
  - pip install codecov
  - codecov
  - bash <(curl -s https://codecov.io/bash) -cF javascript
`

**Comment by TimVanMourik** [comment]
Yes, I would like to see what that does :+1:

**Comment by TimVanMourik** [comment]
Ok! This indeed captures both python and javascript branches, awesome! Although the report looks a bit weird still, as it doesn't mention the python branch. But the 40% coverage is a lot more realistic.

**Comment by aditya-jha** [comment]
Great!
Do you know can we make the reports looks nicer?

**Comment by TimVanMourik** [comment]
I'm looking at the 'merging reports' link that you mentioned. It looks like the
` bash <(curl -s https://codecov.io/bash) -cF [language].`
uploads the latest report to be part of [language]. Which is difficult in the case of the `after-success` statement. But in their example, instead, they run it from the `scripts` part. So how about we do that too? And because it's becoming messy, maybe put everything in a script. So my suggestion is to update the travis yaml script section to:
```
script:
  - bin/codecov.bash
```
and create a file `bin/codecov.bash` along the lines of:
```
#!/bin/bash

# python tests
coverage run ./manage.py test --noinput --settings=app.settings.local
bash <(curl -s https://codecov.io/bash) -cF python

# javascript tests 
npm test
pip install codecov
codecov
bash <(curl -s https://codecov.io/bash) -cF javascript
```

Save typos, because I'm typing this, not copy-pasting. How does that sound?

**Comment by aditya-jha** [comment]
I was thinking the same. Let me try out.

**Comment by TimVanMourik** [comment]
Thanks! Well, it looks nicer in terms of code, but we're back a step as it's not picking up the js anymore... The second upload seems to upload the first report again. This is getting frustrating...

But it makes me wonder, what happens if we swap the python and the javascript bit? At that moment there's no python coverage file yet, so it'll have to upload the js coverage first.

**Comment by aditya-jha** [comment]
@TimVanMourik I reversed the order. How about now? Is the js coverage value correct?

**Comment by TimVanMourik** [comment]
Yes!! It's odd that swapping the order does the trick, but it's working! :D I'll merge this PR and please claim the bounty! Thanks for the help and the many iterations of trial-and-error!

**Comment by aditya-jha** [comment]
Trail and error indeed took long. Hope we can collaborate on further issues/projects. Thanks.

**Pull request merged**
