### PR TITLE
Webpack config

### PR DESCRIPTION
**Pull request by iamonuwa**
## Description
Upgrade webpack from 3.x to 4.x.
Configure webpack 4.x

## Related Issue
#19 
## Motivation and Context
Webpack 4.x has been released and stable

## How Has This Been Tested?
Tested with docker. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by iamonuwa** [comment]
Hey @TimVanMourik, no need for index.html on .gitignore. Initially I didn't know it was generated by webpack. I've removed it and the HtmlWebpackPlugin I used to create it. Everything should work just fine.

Thank you.

**Comment by iamonuwa** [comment]
On the ./bin/docker-command.bash, I set it to run production (npm run build)

**Comment by TimVanMourik** [comment]
Right, hence my question: how do I run the docker locally in development mode?

**Comment by iamonuwa** [comment]
I setup docker to run only on production, I'll make it pick the current environment and run corresponding task now.

**Comment by TimVanMourik** [comment]
What do you think about:
```
# node commands
npm install
node ./bin/pivotNodesByCategory.js;
if [ $NODE_ENV  == production ]; then
  npm run build
elif [ $NODE_ENV  == development ]; then
  npm run dev
else
  npm run build
fi
```

**Comment by iamonuwa** [comment]
So how do you pass it on the terminal? +1

**Comment by TimVanMourik** [comment]
I'm inclined to to it this way, and have only a single docker-compose service. What do you think?

```

# node commands
npm install
node ./bin/pivotNodesByCategory.js;
if   [ NODE_ENV == development ]; then
  npm run dev
elif [ NODE_ENV == production  ]; then
  npm run build
else
  npm run dev
fi
```

**Comment by iamonuwa** [comment]
Can I setup .env file for it?

**Comment by TimVanMourik** [comment]
Yes, that's what I've got now. A .env is automatically read in (if present). There I store my env variables, e.g.:
```
NODE_ENV=development
```
or 
```
NODE_ENV=production
```

**Comment by iamonuwa** [comment]
Great! Had to use push the older one because there was no .env file

**Comment by TimVanMourik** [comment]
Yes, sure: these are all the variables that are used throughout the project. You can add it as your suggested env.sample file.


```
DJANGO_SETTINGS_MODULE=app.settings.local
NODE_ENV=development

CODEFUND_ID=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
GA_ID=UA-000000000-0
DATABASE_URL=postgres://xxxx
GITHUB_API_TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
GITHUB_API_USER=xxxxxxxxxxxx
GITHUB_APP_NAME=xxxxxxxxxxxx
GITHUB_CLIENT_ID=xxxxxxxxxxxxxxxxxxxx
GITHUB_CLIENT_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
SECRET_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
SLACK_API_TOKEN=xxxx-xxxxxxxxxxxx-xxxxxxxxxxxx-xxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

**Comment by iamonuwa** [comment]
Thank you.

**Comment by TimVanMourik** [comment]
Thanks to you :) Please add these last changes, and I'll merge the PR and pay out the bounty!

**Comment by iamonuwa** [comment]
Please review and merge, so that I can start work on the #39

**Comment by iamonuwa** [comment]
Please accept so that I can move to the next one +1

**Comment by TimVanMourik** [comment]
I believe I already accepted the PR and accepted the submission. Anything else?

**Pull request merged**
