### PR TITLE
Linters

### PR DESCRIPTION
**Pull request by nemaniarjun**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by nemaniarjun** [comment]
@TimVanMourik Please review this very carefully. Ask questions whereever you think something is out of place. That would help us find bugs if any. (Main files to review are `.coafile`, `.travis.yml` and the `coala` command in `package.json`

I will start: Why were we running `docker pull timvanmourik/giraffe-tools` ?

**Comment by nemaniarjun** [comment]
The code coverage decreased by 5 lines as I added 5 new line where the line length was > 80

**Comment by TimVanMourik** [comment]
Thanks @nemaniarjun for this work! Let me start answering your question:

> Why were we running docker pull timvanmourik/giraffe-tools on travis?

Good point, uhm, no reason. Looking back at the the version history of the file, at b96c75e75f84fe0a63d1e1974c3dd760feb51ec1 I brought it in without apparent reason. So I'm glad you took it out. In the same commit I introduces the `services: - docker`. That can probably go as well, right?

So the coala docker-command is executed not from within the Docker itself, but from the host. That means that the `npm run coala` command under the hood needs to be platform specific. Contributors from Windows at this moment can't use it because the `$(pwd)` is unix specific.

A solution to this is adding coala to the `docker-compose` file, which I did in 0b447e4691867b5ae799786579fdb6c3481cfebb. Could you please have a look at that? If you run `docker-compose run coala` now, it runs the linter! But this means the coala command is implemented twice: once in the docker-compose, once via npm in the package.json, so ideally I would like to unify this, because that would be more maintainable. So what do you think is the most elegant way to tell Travis to run coala?

Lastly, the `.coafile`. This is completely new to me, but it's quite expressive and clear. I have no comments at this moment but I might look into coala in more detail later on. I think this is excellent for an initial setup! 

And ehh... I will start using double quotation marks from now on 🙄

**Comment by nemaniarjun** [comment]
Will check the `services: -docker` part. 

We can map `npm run coala` to `docker-compose run coala` so that we only have it in one place.

The last thing: You dont have to use double quotations. Thats the beauty, you can write in single quotations and coala will fix it for you! 

The linter doest just checks for style but fixes it too where possible.

Also highly recommended that you install http://prettier.io into your IDE, the joy of `lint on save` is extreme.

**Comment by nemaniarjun** [comment]
I am just waiting for Prettier to support python. It will be beautiful. :)

**Comment by nemaniarjun** [comment]
Checked the adding coala to docker-compose commit. Works properly, this will allow up to lint when the dev runs `docker-compose up`. The correct command for coala would be `docker-compose run coala --rm` as we dont want extra linters' containers filling our docker list.

**Pull request merged**
